### ISSUE TITLE
Receiving to Hosted Channel crashes poncho

### ISSUE THREAD

**Issue by raphjaph** [fiatjaf/poncho#1] opened 2022-08-01 17:54 UTC
I compiled poncho on a RaspberryPi and am running it. It can open a channel to my SBW wallet but as soon as I try to receive some sats it crashes:
```bash
Aug 01 19:39:28 blueberry lightningd[240384]: > poncho: DEBUG   <:: got peer message -- [peer]=02e1381 {Active} [state]=Channel[02e1381]Active(lcss=LastCrossSignedState(5191, balances=100000000msat/0msat, updates=0/0, incomingHtlcs=List(), outgoingHtlcs=List()), uncommitted=List()) [message]=InvokeHostedChannel()
Aug 01 19:39:28 blueberry lightningd[240384]: > poncho: DEBUG   ::> sending LastCrossSignedState(5191, balances=100000000msat/0msat, updates=0/0, incomingHtlcs=List(), outgoingHtlcs=List()) --> 02e1381c6f854f6e586c60ea2b55f3efa570281ea8708ad56fc39c9067e288df4f
Aug 01 19:39:28 blueberry lightningd[240384]: > poncho: DEBUG   <:: got peer message -- [peer]=02e1381 {Active} [state]=Channel[02e1381]Active(lcss=LastCrossSignedState(5191, balances=100000000msat/0msat, updates=0/0, incomingHtlcs=List(), outgoingHtlcs=List()), uncommitted=List()) [message]=LastCrossSignedState(5191, balances=0msat/100000000msat, updates=0/0, incomingHtlcs=List(), outgoingHtlcs=List())
Aug 01 19:39:28 blueberry lightningd[240384]: > poncho: DEBUG   ::> sending LastCrossSignedState(5191, balances=100000000msat/0msat, updates=0/0, incomingHtlcs=List(), outgoingHtlcs=List()) --> 02e1381c6f854f6e586c60ea2b55f3efa570281ea8708ad56fc39c9067e288df4f
Aug 01 19:39:28 blueberry lightningd[240384]: > poncho: DEBUG   ::> sending ChannelUpdate(99f350ad38f27dd3b83739defbe59f95f9c7b53b66e97b3a8d6f523dfa114b23244ec77e183cd1a83706332b950af61280a40baaf805a7fcdb8481e75a055d86,6fe28…,12381032x13769507x15076,1659375568 unixsec,ChannelFlags(true,true),CltvExpiryDelta(143),1000msat,1000msat,1000,Some(100000000msat),TlvStream(List(),List())) --> 02e1381c6f854f6e586c60ea2b55f3efa570281ea8708ad56fc39c9067e288df4f
Aug 01 19:39:28 blueberry lightningd[240384]: > poncho: DEBUG   <:: got peer message -- [peer]=02e1381 {Active} [state]=Channel[02e1381]Active(lcss=LastCrossSignedState(5191, balances=100000000msat/0msat, updates=0/0, incomingHtlcs=List(), outgoingHtlcs=List()), uncommitted=List()) [message]=AskBrandingInfo(24532…)
Aug 01 19:40:31 blueberry lightningd[240384]: java.util.NoSuchElementException: key not found: short_channel_id
Aug 01 19:40:31 blueberry lightningd[240384]:         at java.lang.StackTrace$.currentStackTrace(Unknown Source)
Aug 01 19:40:31 blueberry lightningd[240384]:         at java.lang.Throwable.fillInStackTrace(Unknown Source)
Aug 01 19:40:31 blueberry lightningd[240384]:         at scala.collection.MapOps.default(Unknown Source)
Aug 01 19:40:31 blueberry lightningd[240384]:         at scala.collection.AbstractMap.default(Unknown Source)
Aug 01 19:40:31 blueberry lightningd[240384]:         at scala.collection.MapOps.apply(Unknown Source)
Aug 01 19:40:31 blueberry lightningd[240384]:         at scala.collection.AbstractMap.apply(Unknown Source)
Aug 01 19:40:31 blueberry lightningd[240384]:         at ujson.Value$Selector$StringSelector.apply(Unknown Source)
Aug 01 19:40:31 blueberry lightningd[240384]:         at ujson.Value.apply(Unknown Source)
Aug 01 19:40:31 blueberry lightningd[240384]:         at ujson.Obj.apply(Unknown Source)
Aug 01 19:40:31 blueberry lightningd[240384]:         at CLN.handleRPC$$anonfun$12(Unknown Source)
Aug 01 19:40:31 blueberry lightningd[240384]:         at CLN$$Lambda$44.apply$mcV$sp(Unknown Source)
Aug 01 19:40:31 blueberry lightningd[240384]:         at scala.scalanative.loop.Timer$.$init$$$anonfun$1(Unknown Source)
Aug 01 19:40:31 blueberry lightningd[240384]:         at <none>._SM39scala.scalanative.loop.Timer$$$Lambda$1G17$extern$forwarder(Unknown Source)
Aug 01 19:40:31 blueberry lightningd[240384]:         at <none>.(Unknown Source)
Aug 01 19:40:31 blueberry lightningd[240384]:         at <none>.uv_run(Unknown Source)
Aug 01 19:40:31 blueberry lightningd[240384]:         at scala.scalanative.loop.EventLoop$.run(Unknown Source)
Aug 01 19:40:31 blueberry lightningd[240384]:         at scala.scalanative.loop.EventLoop$$anon$1.run(Unknown Source)
Aug 01 19:40:31 blueberry lightningd[240384]:         at scala.scalanative.runtime.ExecutionContext$.loop(Unknown Source)
Aug 01 19:40:31 blueberry lightningd[240384]:         at scala.scalanative.runtime.package$.loop(Unknown Source)
Aug 01 19:40:31 blueberry lightningd[240384]:         at <none>.main(Unknown Source)
Aug 01 19:40:31 blueberry lightningd[240384]:         at <none>.(Unknown Source)
Aug 01 19:40:31 blueberry lightningd[240384]:         at <none>.__libc_start_main(Unknown Source)
Aug 01 19:40:31 blueberry lightningd[240384]:         at <none>._start(Unknown Source)
Aug 01 19:40:31 blueberry lightningd[240349]: INFO    plugin-poncho-out: Killing plugin: exited during normal operation
```

Before crashing this is the output of `hc-list`:
```
[
   {
      "peer_id": "02e1381c6f854f6e586c60ea2b55f3efa570281ea8708ad56fc39c9067e288df4f",
      "channel_id": "24532e7691ebf48e881be80c80272a573652abde13dea404f4a56dab31a31561",
      "short_channel_id": "12381032x13769507x15076",
      "status": "active",
      "data": {
         "is_host": true,
         "blockday": 5191,
         "local_errors": [],
         "remote_errors": [],
         "local_updates": "0",
         "remote_updates": "0",
         "balance": {
            "total": "100000000",
            "local": "100000000",
            "remote": "0"
         },
         "incoming_htlcs": [],
         "outgoing_htlcs": [],
         "uncommitted_updates": 0
      }
   }
]
```

This is some of the infos SBW shows:
```
Local wallet node ID
02e1381c6f854f6e586c60ea2b55f3efa570281ea8708ad56fc39c9067e288df4f

Channel short ID
-4833654523444380956
```

Normal receiving to the Motherbase Hosted Channel works so I don't think it's SBW's fault.

**Comment by fiatjaf** [comment] 2022-08-01 18:41
This crash is caused by you not running CLN on the latest `master`. I'm sorry, I forgot to note that on the README. Fixed now.

**Closed** 2022-08-01 18:41 UTC
